# Generated by Django 4.1.1 on 2024-05-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
